#ifndef LEVEL_IDS_H
#define LEVEL_IDS_H

typedef enum LevelId
{
    SUNRISE_SPRING = 10,
    SUNNY_VILLA = 11,
    CLOUD_SPIRES = 12,
    MOLTEN_CRATER = 13,
    SEASHELL_SHORE = 14,
    MUSHROOM_SPEEDWAY = 15,
    SHEILAS_ALP = 16,
    BUZZS_DUNGEON = 17,
    CRAWDAD_FARM = 18,

    MIDDAY_GARDEN = 20,
    ICY_PEAK = 21,
    ENCHANTED_TOWERS = 22,
    SPOOKY_SWAMP = 23,
    BAMBOO_TERRACE = 24,
    COUNTRY_SPEEDWAY = 25,
    SGT_BYRDS_BASE = 26,
    SPIKES_ARENA = 27,
    SPIDER_TOWN = 28,

    EVENING_LAKE = 30,
    FROZEN_ALTARS = 31,
    LOST_FLEET = 32,
    FIREWORKS_FACTORY = 33,
    CHARMED_RIDGE = 34,
    HONEY_SPEEDWAY = 35,
    BENTLEYS_OUTPOST = 36,
    SCORCHS_PIT = 37,
    STARFISH_REEF = 38,

    MIDNIGHT_MOUNTAIN = 40,
    CRYSTAL_ISLANDS = 41,
    DESERT_RUINS = 42,
    HAUNTED_TOMB = 43,
    DINO_MINES = 44,
    HARBOR_SPEEDWAY = 45,
    AGENT_9S_LAB = 46,
    SORCERESS_LAIR = 47,
    BUGBOT_FACTORY = 48,

    SUPER_BONUS_ROUND = 50,

    AN_EVIL_PLOT_UNFOLDS = 61,
    THE_SECOND_WARNING = 62,
    BIANCA_STRIKES_BACK = 63,
    HUNTERS_TUSSLE = 64,
    SPIKE_IS_BORN = 65,
    AN_APOLOGY_AND_LUNCH = 66,
    A_MONSTER_TO_END_ALL_MONSTERS = 67,
    THE_ESCAPE = 68,
    DEJA_VU = 69,
    A_FAMILIAR_FACE = 70,
    BILLY_IN_THE_WALL = 71,
    REMOVED_CUTSCENE = 72,
    ONE_LESS_NOBLE_WARRIOR = 73,
    THE_END = 74,
    A_POWERFUL_VILLAIN_EMERGES = 75,
    A_DESPERATE_RESCUE_BEGINS = 76,
    NO_HARD_FEELINGS = 77,
    BYRD_JAMES_BYRD = 78,
    A_DUPLICITOUS_LARCENOUS_URSINE = 79,
    THE_DANCING_BEAR = 80
} LevelId;

#endif /* LEVEL_IDS_H */
