#ifndef TEXT_COLORS
#define TEXT_COLORS

typedef enum TextColor
{
    COLOR_BROWN,
    COLOR_YELLOW,
    COLOR_GOLD_AGAIN,
    COLOR_WHITE,
    COLOR_GREEN,
    COLOR_CREAM,
    COLOR_BRIGHT_YELLOW,
    COLOR_BRONZE,
    COLOR_ORANGE,
    COLOR_PEACH,
    COLOR_DARK_GOLD,
    COLOR_BRIGHT_ORANGE,
    COLOR_SUN_YELLOW,
    COLOR_DARK_GREY
}TextColor;

#endif // TEXT_COLORS
